website/models.py
#from email.policy import default
from datetime import datetime

from . import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    first_name = db.Column(db.String(100))
    last_name = db.Column(db.String(100))
    password = db.Column(db.String(100))
    role = db.Column(db.String(10))
    tickets = db.relationship('Ticket', backref='user')


class Ticket(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    title = db.Column(db.String(100))
    description = db.Column(db.String(600))
    date_added = db.Column(db.DateTime, default=datetime.utcnow)

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

from os import path

db = SQLAlchemy()
DB_NAME = "database.db"

def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('DataBAse CREATED')

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'Entry1234' # This is needed to enable POST requests
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}' # This sets the location of the database
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    create_database(app)

    from .models import User

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

app = create_app()

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint("auth", __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password.', category='error')
        else:
            flash('User does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        last_name = request.form.get('lastName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        role = request.form.get('role')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 4 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif len(last_name) < 2:
            flash('Last name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Password do not match.', category='error')
        elif len(password1) < 7:
            flash('Password must be longer than 7 characters', category='error')
        else:
            new_user = User(email=email, first_name=first_name,
                            last_name=last_name, password=generate_password_hash(password1), role=role)
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

website/views.py
from datetime import datetime

from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user

from . import db
from .models import Ticket, User

views = Blueprint("views", __name__)


@views.route("/")
@login_required
def home():
    return render_template("home.html", user=current_user)


@views.route("/contact/")
def contact():
    return render_template("contact.html", user=current_user)


@views.route("/tickets/")
def tickets():
    # Get the headings for the Ticket table
    headings = Ticket.__table__.columns
    formatted_headings = []
    for header in headings:
        if 'user_id' in str(header):
            formatted_headings.append('Owner')
        else:
            formatted_headings.append(
                str(header).replace('ticket.', '').capitalize().replace('_', ' '))

    tickets = db.session.query(Ticket).filter(
        Ticket.user_id == current_user.id)
    tickets = db.session.query(Ticket)
    my_tickets = []
    remaining_tickets = []
    for ticket in tickets:
        user = db.session.query(User).filter(User.id == ticket.user_id).first()
        if ticket.user_id == current_user.id:
            my_tickets.append(
                [ticket.id, user.email, ticket.title, ticket.description, ticket.date_added])
        else:
            remaining_tickets.append(
                [ticket.id, user.email, ticket.title, ticket.description, ticket.date_added])

    return render_template("tickets.html", user=current_user, headings=formatted_headings, my_tickets=my_tickets, remaining_tickets=remaining_tickets)


@views.route("/create/", methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        title = request.form.get('title')
        description = request.form.get('description')

        new_ticket = Ticket(
            title=title, description=description, user=current_user)
        db.session.add(new_ticket)
        db.session.commit()
        flash('Ticket created!', category='success')
        return redirect(url_for('views.tickets'))

    return render_template("create_ticket.html", user=current_user)


@views.route("/update/<int:id>", methods=['GET', 'POST'])
def update(id):
    ticket_to_update = Ticket.query.get_or_404(id)
    if request.method == 'POST':
        ticket_to_update.title = request.form.get('title')
        ticket_to_update.description = request.form.get('description')

        try:
            db.session.commit()
            flash('Ticket Updated!', category='success')
            return redirect(url_for('views.tickets'))
        except:
            raise RuntimeError("There was an error when updating the ticket")
    return render_template("update_ticket.html", user=current_user, ticket_to_update=ticket_to_update)


@views.route("/delete/<int:id>")
def delete(id):
    ticket_to_delete = Ticket.query.get_or_404(id)
    try:
        db.session.delete(ticket_to_delete)
        db.session.commit()
        flash('Ticket successfully deleted!', category='success')
        return redirect(url_for('views.tickets'))
    except:
        return RuntimeError("Error when deleting the ticket")


@views.route("/users/")
def users():
    # Get the headings for the Ticket table
    headings = User.__table__.columns
    formatted_headings = []
    for header in headings:
        if 'password' in str(header):
            continue
        formatted_headings.append(
            str(header).replace('user.', '').capitalize().replace('_', ' '))

    users = db.session.query(User)
    filtered_users = []
    for user in users:
        filtered_users.append(
            [user.id, user.email, user.first_name, user.last_name, user.role])

    return render_template("users.html", user=current_user, headings=formatted_headings, data=filtered_users)


@views.route("/api/data")
def get_data():
    return views.send_static_file("data.json")

website/templates/contact.html
{% extends "layout.html" %} {% block title %} Contact {% endblock %} {% block
content %}
<p>email: customerservice@ticketsystem.com</p>
{% endblock %}

website/templates/create_ticket.html
{% extends "layout.html" %} {% block title %} Create Ticket {% endblock %} {%
block content %}
<form method="POST">
  <h3 align="center">Create Ticket</h3>
  <div class="form-group">
    <label for="title">Title</label>
    <input
      type="title"
      class="form-control"
      id="title"
      name="title"
      placeholder="Enter title"
    />
  </div>
  <div class="form-group">
    <label for="description">Description</label>
    <input
      type="description"
      class="form-control"
      id="description"
      name="description"
      placeholder="Enter description"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Create</button>
</form>
{% endblock %}

website/templates/hello_there.html
<!DOCTYPE html>
<html>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='site.css')}}" />
    <head>
        <meta charset="utf-8" />
        <title>Hello, Flask</title>
    </head>
    <h1><span class="title">Welcome to Flask</span></h1>
    <body>
        <p>
        {%if name %}
            <span class="message">Hello there, {{ name }}!</span> It's {{ date.strftime("%A, %d %B, %Y at %X") }}.
        {% else %}
            <span class="footer">What's your name? Provide it after /hello/ in the URL.</span>
        {% endif %}
        </p>
    </body>
</html>

website/templates/home.html
{% extends "layout.html" %} {% block title %} Home {% endblock %} {% block
content %}
<p>Welcome to your home page</p>
{% endblock %}

website/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %}{% endblock %}</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='site.css')}}"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a
            href="{{ url_for('views.home') }}"
            class="nav-item nav-link"
            id="home"
            >Home</a
          >
          <a
            href="{{ url_for('views.tickets') }}"
            class="nav-item nav-link"
            id="tickets"
            >Tickets</a
          >
          <a
            href="{{ url_for('views.users') }}"
            class="nav-item nav-link"
            id="users"
            >Users</a
          >
          <a
            href="{{ url_for('auth.logout') }}"
            class="nav-item nav-link"
            id="logout"
            >Log Out</a
          >
          {% else %}
          <a
            href="{{ url_for('auth.login') }}"
            class="nav-item nav-link"
            id="login"
            >Log In</a
          >
          <a
            href="{{ url_for('auth.sign_up') }}"
            class="nav-item nav-link"
            id="signup"
            >Sign Up</a
          >
          <a
            href="{{ url_for('views.contact') }}"
            class="nav-item nav-link"
            id="contacts"
            >Contact</a
          >
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="body-content container">
      {% block content %} {% endblock %}
      <hr />
      <footer>
        <p>© 2022</p>
      </footer>
    </div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

website/templates/login.html
{% extends "layout.html" %} {% block title %} Login {% endblock %} {% block
content %}
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/sign_up.html
{% extends "layout.html" %} {% block title %} Sign Up {% endblock %} {% block
content %}
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
    <label for="lastName">Last Name</label>
    <input
      type="text"
      class="form-control"
      id="lastName"
      name="lastName"
      placeholder="Enter last name"
    />
  </div>
  <div class="form-group">
    <label for="role">Role</label> <br />
    <input type="radio" id="admin" name="role" value="admin" /><label
      for="admin"
      >Admin</label
    ><br />
    <input type="radio" id="user" name="role" value="user" /><label for="user"
      >User</label
    ><br />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Confirm Password</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

website/templates/tickets.html
{% extends "layout.html" %} {% block title %} Tickets {% endblock %} {% block
content %}
<h3 align="center">My Tickets</h3>
<table class="table">
  <tr class="table__header">
    {% for header in headings %}
    <th class="table__cell">{{ header }}</th>
    {% endfor %}
  </tr>
  {% for row in my_tickets %}
  <tr class="table__row">
    {% for cell in row %}
    <td class="table__cell">{{ cell }}</td>
    {% endfor %}
    <td> <a href="{{ url_for('views.update', id=row[0]) }}" class="btn btn-outline-warning btn-sm">Update</td>
    {% if user.role == 'admin' %}
    <td> <a href="{{ url_for('views.delete', id=row[0]) }}" class="btn btn-outline-danger btn-sm">Delete</td>
    {% endif %}
    </tr>
  {% endfor %}
</table>
<div align="right"><a href="{{ url_for('views.create') }}" class="btn btn-primary btn-sm">Create Ticket</a></div>
</br>
<h3 align="center">Other Tickets</h3>
<table class="table">
  <tr class="table__header">
    {% for header in headings %}
    <th class="table__cell">{{ header }}</th>
    {% endfor %}
  </tr>
  {% for row in remaining_tickets %}
  <tr class="table__row">
    {% for cell in row %}
    <td class="table__cell">{{ cell }}</td>
    {% endfor %}
    {% if user.role == 'admin' %}
    <td> <a href="{{ url_for('views.update', id=row[0]) }}" class="btn btn-outline-warning btn-sm">Update</td>
    <td> <a href="{{ url_for('views.delete', id=row[0]) }}" class="btn btn-outline-danger btn-sm">Delete</td>
    {% endif %}
    </tr>
  {% endfor %}
</table>
{% endblock %}

website/templates/update_ticket.html
{% extends "layout.html" %} {% block title %} Update Ticket {% endblock %} {%
block content %}
<form method="POST">
  <h3 align="center">Update Ticket</h3>
  <div class="form-group">
    <label for="title">Title</label>
    <input
      type="title"
      class="form-control"
      id="title"
      name="title"
      placeholder="Enter title"
    />
  </div>
  <div class="form-group">
    <label for="description">Description</label>
    <input
      type="description"
      class="form-control"
      id="description"
      name="description"
      placeholder="Enter description"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock %}

website/templates/users.html
{% extends "layout.html" %} {% block title %} Users {% endblock %} {% block
    content %}
    <h3 align="center">Users</h3>
    <table class="table">
      <tr class="table__header">
        {% for header in headings %}
        <th class="table__cell">{{ header }}</th>
        {% endfor %}
      </tr>
      {% for row in data %}
      <tr class="table__row">
        {% for cell in row %}
        <td class="table__cell">{{ cell }}</td>
        {% endfor %}
        {% if user.role == 'admin' %}
        <td> <a href="{{ url_for('views.delete', id=row[0]) }}" class="btn btn-outline-danger btn-sm">Delete</td>
        {% endif %}
        </tr>
      {% endfor %}
    </table>
    {% endblock %}